#!/bin/sh

# Source system X11 configuration environment variables
if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# Execute your customized Qtile-MATE script
exec /usr/local/bin/qtile-mate-session
