[Settings]
gtk-theme-name =BlackMATE
gtk-icon-theme-name =rami
# GTK3 ignores bold or italic attributes.
gtk-font-name = FreeMono 10
gtk-menu-images = 1
gtk-button-images = 1
#gtk-toolbar-style = GTK_TOOLBAR_BOTH_HORIZ
gtk-cursor-theme-name = Breeze_Snow
