# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
#[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
    # We have color support; assume it's compliant with Ecma-48
    # (ISO/IEC-6429). (Lack of such support is extremely rare, and such
    # a case would tend to support setf rather than setaf.)
    color_prompt=yes
    else
    color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then

    #PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
    PROMPT_DIRTRIM=2

    GRAY="\[\e[90m\]"
    TEAL="\[\e[36m\]"
    GOLD="\[\e[33m\]"
    GREEN="\[\e[32m\]"
    LIGHT_GRAY="\[\e[37m\]"
    RESET="\[\e[0m\]"
    BLOCK=$'\342\226\225'

    YELLOW="\[\033[01;33m\]"
    THIN_LINE=$'\342\224\202'
    THIN_BLOCK=$'\342\226\225'

    time_datex() { date +"%A %d %B %T"; }

    dir_files() {
        local files
        files=$(ls -1A | wc -l)
        printf "%s" "$files"
    }



    dir_size() {
        local size
        size=$(du -sh . 2>/dev/null | awk '{print $1}')

        if [ -z "$size" ]; then
            size="0B (Access Denied)"
        fi

        printf "%s" "$size"
    }

    draw_line() {
        "$@" 2>&1 | awk '{print "\033[97m\342\226\225\033[0m " $0}'
    }

    command_not_found_handle() {
        local err_msg="bash: $1: command not found"
        echo "$err_msg" | awk '{print "\033[90m\342\226\225\033[0m " $0}'
        return 127
    }

    #PS1="${GRAY}${BLOCK} ${TEAL}\u@\h ${GOLD}>> ${GREEN}\w${LIGHT_GRAY} [${LIGHT_GRAY} files : ${TEAL}\$(dir_files), ${LIGHT_GRAY} Size : ${GOLD}\$(dir_size)${LIGHT_GRAY}]${RESET}\n${GRAY}${BLOCK} ${LIGHT_GRAY}\$(time_datex) ${RESET}\n${GRAY}${BLOCK} ${GOLD}λ ${RESET}"
    PS1="${GRAY}${BLOCK} ${TEAL}\u@\h ${GOLD}>> ${GREEN}\w${LIGHT_GRAY} [${LIGHT_GRAY} files : ${TEAL}\$(dir_files),${LIGHT_GRAY} Size : ${GOLD}\$(dir_size)${LIGHT_GRAY}]${RESET}\n"
    PS1+="${GRAY}${BLOCK} ${LIGHT_GRAY}\$(time_datex) ${RESET}\n"
    PS1+="${GRAY}${BLOCK} ${GOLD}λ ${RESET}"

else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='draw_line command ls --color=always'
    alias dir='draw_line command dir --color=always'
    alias vdir='draw_line command vdir --color=always'
    alias df='draw_line command df'

    alias grep='draw_line command grep --color=always'
    alias fgrep='draw_line command fgrep --color=always'
    alias egrep='draw_line command egrep --color=always'
    alias pwd='draw_line command pwd'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
#alias ll='ls -l'
#alias la='ls -A'
#alias l='ls -CF'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi
export NO_AT_BRIDGE=1

# Created by `pipx` on 2026-09-06 16:35:58
export PATH="$PATH:/home/rtx/.local/bin"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/rtx/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/rtx/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/rtx/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/rtx/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

# Automatically start X11 on TTY1 text login
if [ -z "$DISPLAY" ] && [ "$XDG_VTNR" -eq 1 ]; then
    exec startx
fi
. "$HOME/.cargo/env"
